spring.application.name=vocabulary-backend

spring.web.resources.static-locations=file:./audio/
# Neo4j
spring.neo4j.uri=bolt://localhost:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=${NEO4J_PASSWORD}

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/vocabulary_progress
spring.datasource.username=postgres
spring.datasource.password=${PG_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

# Порт сервера
server.port=8080